/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : S:/CLionProjects/korenkov/Grammar.g
 *     -                            On : 2025-12-10 19:27:20
 *     -                 for the lexer : GrammarLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
GrammarLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pGrammarLexer, which is returned from a call to GrammarLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pGrammarLexer are  as follows:
 *
 *  - 
 void
      pGrammarLexer->T__82(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__83(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__84(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__85(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__86(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__87(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__88(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__89(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__90(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__91(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__92(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__93(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__94(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__95(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__96(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__97(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__98(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__99(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__100(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__101(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__102(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->T__103(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->LETTER(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->DIGIT(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->WS(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_TRUE(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_FALSE(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_METHOD(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_VAR(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_IF(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_THEN(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_ELSE(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_BEGIN(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_END(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_WHILE(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_DO(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_REPEAT(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_UNTIL(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_BREAK(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_OF(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_ARRAY(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_BOOL(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_BYTE(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_INT(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_UINT(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_LONG(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_ULONG(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_CHAR(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->K_STRING(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->IDENTIFIER(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->STRING(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->CHAR(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->HEX(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->BITS(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->DEC(pGrammarLexer)
 *  - 
 void
      pGrammarLexer->Tokens(pGrammarLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_GrammarLexer_H
#define _GrammarLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct GrammarLexer_Ctx_struct GrammarLexer, * pGrammarLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
GrammarLexer

 */
struct GrammarLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__82)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__83)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__84)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__85)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__86)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__87)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__88)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__89)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__90)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__91)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__92)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__93)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__94)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__95)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__96)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__97)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__98)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__99)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__100)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__101)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__102)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mT__103)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mLETTER)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mDIGIT)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_TRUE)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_FALSE)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_METHOD)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_VAR)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_IF)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_THEN)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_ELSE)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_BEGIN)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_END)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_WHILE)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_DO)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_REPEAT)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_UNTIL)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_BREAK)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_OF)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_ARRAY)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_BOOL)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_BYTE)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_INT)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_UINT)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_LONG)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_ULONG)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_CHAR)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mK_STRING)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mIDENTIFIER)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mSTRING)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mCHAR)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mHEX)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mBITS)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mDEC)	(struct GrammarLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct GrammarLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct GrammarLexer_Ctx_struct * ctx);
    void	    (*free)   (struct GrammarLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pGrammarLexer GrammarLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pGrammarLexer GrammarLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__82      82
#define T__83      83
#define T__84      84
#define T__85      85
#define T__86      86
#define T__87      87
#define T__88      88
#define T__89      89
#define T__90      90
#define T__91      91
#define T__92      92
#define T__93      93
#define T__94      94
#define T__95      95
#define T__96      96
#define T__97      97
#define T__98      98
#define T__99      99
#define T__100      100
#define T__101      101
#define T__102      102
#define T__103      103
#define ADD      4
#define AND      5
#define ARGUMENTS      6
#define ARRAY_ELEMENT      7
#define ARRAY_ELEMENT_INDEX      8
#define ARRAY_ID      9
#define ASSIGN      10
#define BITS      11
#define BLOCK      12
#define BODY      13
#define BREAK      14
#define CALL      15
#define CHAR      16
#define CONDITION      17
#define DEC      18
#define DIGIT      19
#define DIVISION      20
#define DO      21
#define ELSE      22
#define EQUALS      23
#define EXPRESSION      24
#define HEX      25
#define ID      26
#define IDENTIFIER      27
#define IF      28
#define IN_BRACES      29
#define K_ARRAY      30
#define K_BEGIN      31
#define K_BOOL      32
#define K_BREAK      33
#define K_BYTE      34
#define K_CHAR      35
#define K_DO      36
#define K_ELSE      37
#define K_END      38
#define K_FALSE      39
#define K_IF      40
#define K_INT      41
#define K_LONG      42
#define K_METHOD      43
#define K_OF      44
#define K_REPEAT      45
#define K_STRING      46
#define K_THEN      47
#define K_TRUE      48
#define K_UINT      49
#define K_ULONG      50
#define K_UNTIL      51
#define K_VAR      52
#define K_WHILE      53
#define LESS_THAN      54
#define LESS_THAN_OR_EQUALS      55
#define LETTER      56
#define METHOD_DECL      57
#define MORE_THAN      58
#define MORE_THAN_OR_EQUALS      59
#define MULTIPLY      60
#define NOT_EQUALS      61
#define OR      62
#define PARAMETER      63
#define PARAMETERS      64
#define REPEAT      65
#define REPEATABLE_PART      66
#define RESIDUE      67
#define RETURN_TYPE      68
#define SOURCE      69
#define STRING      70
#define SUBTRACT      71
#define THEN      72
#define TYPE      73
#define UNARY_OPERATION      74
#define VALUE      75
#define VARIABLES      76
#define VAR_DECLARATION      77
#define VAR_DECLARATIONS      78
#define VOID_VALUE      79
#define WHILE      80
#define WS      81
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for GrammarLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
