/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : S:/CLionProjects/MyCompiler/Grammar.g
 *     -                            On : 2025-12-14 19:20:03
 *     -                for the parser : GrammarParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
GrammarParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pGrammarParser, which is returned from a call to GrammarParserNew().
 *
 * The methods in pGrammarParser are  as follows:
 *
 *  - 
 GrammarParser_source_return
      pGrammarParser->source(pGrammarParser)
 *  - 
 GrammarParser_sourceItem_return
      pGrammarParser->sourceItem(pGrammarParser)
 *  - 
 GrammarParser_typeRef_return
      pGrammarParser->typeRef(pGrammarParser)
 *  - 
 GrammarParser_commaList_return
      pGrammarParser->commaList(pGrammarParser)
 *  - 
 GrammarParser_builtinType_return
      pGrammarParser->builtinType(pGrammarParser)
 *  - 
 GrammarParser_funcDef_return
      pGrammarParser->funcDef(pGrammarParser)
 *  - 
 GrammarParser_funcSignature_return
      pGrammarParser->funcSignature(pGrammarParser)
 *  - 
 GrammarParser_methodName_return
      pGrammarParser->methodName(pGrammarParser)
 *  - 
 GrammarParser_methodParameter_return
      pGrammarParser->methodParameter(pGrammarParser)
 *  - 
 GrammarParser_methodParameters_return
      pGrammarParser->methodParameters(pGrammarParser)
 *  - 
 GrammarParser_methodReturnType_return
      pGrammarParser->methodReturnType(pGrammarParser)
 *  - 
 GrammarParser_methodBody_return
      pGrammarParser->methodBody(pGrammarParser)
 *  - 
 GrammarParser_varDeclaration_return
      pGrammarParser->varDeclaration(pGrammarParser)
 *  - 
 GrammarParser_variableNameList_return
      pGrammarParser->variableNameList(pGrammarParser)
 *  - 
 GrammarParser_statement_return
      pGrammarParser->statement(pGrammarParser)
 *  - 
 GrammarParser_ifStatement_return
      pGrammarParser->ifStatement(pGrammarParser)
 *  - 
 GrammarParser_whileStatement_return
      pGrammarParser->whileStatement(pGrammarParser)
 *  - 
 GrammarParser_repeatStatement_return
      pGrammarParser->repeatStatement(pGrammarParser)
 *  - 
 GrammarParser_breakStatement_return
      pGrammarParser->breakStatement(pGrammarParser)
 *  - 
 GrammarParser_statementBlock_return
      pGrammarParser->statementBlock(pGrammarParser)
 *  - 
 GrammarParser_expressionStatement_return
      pGrammarParser->expressionStatement(pGrammarParser)
 *  - 
 GrammarParser_expression_return
      pGrammarParser->expression(pGrammarParser)
 *  - 
 GrammarParser_assignExpression_return
      pGrammarParser->assignExpression(pGrammarParser)
 *  - 
 GrammarParser_calculationExpression_return
      pGrammarParser->calculationExpression(pGrammarParser)
 *  - 
 GrammarParser_orExpression_return
      pGrammarParser->orExpression(pGrammarParser)
 *  - 
 GrammarParser_andExpression_return
      pGrammarParser->andExpression(pGrammarParser)
 *  - 
 GrammarParser_eqExpression_return
      pGrammarParser->eqExpression(pGrammarParser)
 *  - 
 GrammarParser_equalOperator_return
      pGrammarParser->equalOperator(pGrammarParser)
 *  - 
 GrammarParser_relExpression_return
      pGrammarParser->relExpression(pGrammarParser)
 *  - 
 GrammarParser_compareOperator_return
      pGrammarParser->compareOperator(pGrammarParser)
 *  - 
 GrammarParser_addExpression_return
      pGrammarParser->addExpression(pGrammarParser)
 *  - 
 GrammarParser_plusSubtractOperator_return
      pGrammarParser->plusSubtractOperator(pGrammarParser)
 *  - 
 GrammarParser_mulExpression_return
      pGrammarParser->mulExpression(pGrammarParser)
 *  - 
 GrammarParser_mulOperator_return
      pGrammarParser->mulOperator(pGrammarParser)
 *  - 
 GrammarParser_unaryExpression_return
      pGrammarParser->unaryExpression(pGrammarParser)
 *  - 
 GrammarParser_unaryOp_return
      pGrammarParser->unaryOp(pGrammarParser)
 *  - 
 GrammarParser_primaryExpr_return
      pGrammarParser->primaryExpr(pGrammarParser)
 *  - 
 GrammarParser_callExpression_return
      pGrammarParser->callExpression(pGrammarParser)
 *  - 
 GrammarParser_argumentList_return
      pGrammarParser->argumentList(pGrammarParser)
 *  - 
 GrammarParser_bracesExpression_return
      pGrammarParser->bracesExpression(pGrammarParser)
 *  - 
 GrammarParser_indexerExpression_return
      pGrammarParser->indexerExpression(pGrammarParser)
 *  - 
 GrammarParser_placeExpression_return
      pGrammarParser->placeExpression(pGrammarParser)
 *  - 
 GrammarParser_literal_return
      pGrammarParser->literal(pGrammarParser)
 * 
 * 
 * 
 * 
 * 
 * 
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_GrammarParser_H
#define _GrammarParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct GrammarParser_Ctx_struct GrammarParser, * pGrammarParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */

typedef struct GrammarParser_source_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_source_return;



typedef struct GrammarParser_sourceItem_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_sourceItem_return;



typedef struct GrammarParser_typeRef_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_typeRef_return;



typedef struct GrammarParser_commaList_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_commaList_return;



typedef struct GrammarParser_builtinType_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_builtinType_return;



typedef struct GrammarParser_funcDef_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_funcDef_return;



typedef struct GrammarParser_funcSignature_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_funcSignature_return;



typedef struct GrammarParser_methodName_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_methodName_return;



typedef struct GrammarParser_methodParameter_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_methodParameter_return;



typedef struct GrammarParser_methodParameters_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_methodParameters_return;



typedef struct GrammarParser_methodReturnType_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_methodReturnType_return;



typedef struct GrammarParser_methodBody_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_methodBody_return;



typedef struct GrammarParser_varDeclaration_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_varDeclaration_return;



typedef struct GrammarParser_variableNameList_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_variableNameList_return;



typedef struct GrammarParser_statement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_statement_return;



typedef struct GrammarParser_ifStatement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_ifStatement_return;



typedef struct GrammarParser_whileStatement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_whileStatement_return;



typedef struct GrammarParser_repeatStatement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_repeatStatement_return;



typedef struct GrammarParser_breakStatement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_breakStatement_return;



typedef struct GrammarParser_statementBlock_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_statementBlock_return;



typedef struct GrammarParser_expressionStatement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_expressionStatement_return;



typedef struct GrammarParser_expression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_expression_return;



typedef struct GrammarParser_assignExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_assignExpression_return;



typedef struct GrammarParser_calculationExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_calculationExpression_return;



typedef struct GrammarParser_orExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_orExpression_return;



typedef struct GrammarParser_andExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_andExpression_return;



typedef struct GrammarParser_eqExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_eqExpression_return;



typedef struct GrammarParser_equalOperator_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_equalOperator_return;



typedef struct GrammarParser_relExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_relExpression_return;



typedef struct GrammarParser_compareOperator_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_compareOperator_return;



typedef struct GrammarParser_addExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_addExpression_return;



typedef struct GrammarParser_plusSubtractOperator_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_plusSubtractOperator_return;



typedef struct GrammarParser_mulExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_mulExpression_return;



typedef struct GrammarParser_mulOperator_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_mulOperator_return;



typedef struct GrammarParser_unaryExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_unaryExpression_return;



typedef struct GrammarParser_unaryOp_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_unaryOp_return;



typedef struct GrammarParser_primaryExpr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_primaryExpr_return;



typedef struct GrammarParser_callExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_callExpression_return;



typedef struct GrammarParser_argumentList_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_argumentList_return;



typedef struct GrammarParser_bracesExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_bracesExpression_return;



typedef struct GrammarParser_indexerExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_indexerExpression_return;



typedef struct GrammarParser_placeExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_placeExpression_return;



typedef struct GrammarParser_literal_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GrammarParser_literal_return;




/** Context tracking structure for 
GrammarParser

 */
struct GrammarParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     GrammarParser_source_return
     (*source)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_sourceItem_return
     (*sourceItem)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_typeRef_return
     (*typeRef)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_commaList_return
     (*commaList)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_builtinType_return
     (*builtinType)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_funcDef_return
     (*funcDef)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_funcSignature_return
     (*funcSignature)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_methodName_return
     (*methodName)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_methodParameter_return
     (*methodParameter)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_methodParameters_return
     (*methodParameters)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_methodReturnType_return
     (*methodReturnType)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_methodBody_return
     (*methodBody)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_varDeclaration_return
     (*varDeclaration)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_variableNameList_return
     (*variableNameList)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_statement_return
     (*statement)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_ifStatement_return
     (*ifStatement)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_whileStatement_return
     (*whileStatement)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_repeatStatement_return
     (*repeatStatement)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_breakStatement_return
     (*breakStatement)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_statementBlock_return
     (*statementBlock)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_expressionStatement_return
     (*expressionStatement)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_expression_return
     (*expression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_assignExpression_return
     (*assignExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_calculationExpression_return
     (*calculationExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_orExpression_return
     (*orExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_andExpression_return
     (*andExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_eqExpression_return
     (*eqExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_equalOperator_return
     (*equalOperator)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_relExpression_return
     (*relExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_compareOperator_return
     (*compareOperator)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_addExpression_return
     (*addExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_plusSubtractOperator_return
     (*plusSubtractOperator)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_mulExpression_return
     (*mulExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_mulOperator_return
     (*mulOperator)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_unaryExpression_return
     (*unaryExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_unaryOp_return
     (*unaryOp)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_primaryExpr_return
     (*primaryExpr)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_callExpression_return
     (*callExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_argumentList_return
     (*argumentList)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_bracesExpression_return
     (*bracesExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_indexerExpression_return
     (*indexerExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_placeExpression_return
     (*placeExpression)	(struct GrammarParser_Ctx_struct * ctx);

     GrammarParser_literal_return
     (*literal)	(struct GrammarParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred1_Grammar)	(struct GrammarParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred2_Grammar)	(struct GrammarParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred3_Grammar)	(struct GrammarParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred4_Grammar)	(struct GrammarParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred5_Grammar)	(struct GrammarParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred6_Grammar)	(struct GrammarParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct GrammarParser_Ctx_struct * ctx);
    void	    (*free)   (struct GrammarParser_Ctx_struct * ctx);
/* @headerFile.members() */
pANTLR3_BASE_TREE_ADAPTOR	adaptor;
pANTLR3_VECTOR_FACTORY		vectors;
/* End @headerFile.members() */
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pGrammarParser GrammarParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pGrammarParser GrammarParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__83      83
#define T__84      84
#define T__85      85
#define T__86      86
#define T__87      87
#define T__88      88
#define T__89      89
#define T__90      90
#define T__91      91
#define T__92      92
#define T__93      93
#define T__94      94
#define T__95      95
#define T__96      96
#define T__97      97
#define T__98      98
#define T__99      99
#define T__100      100
#define T__101      101
#define T__102      102
#define T__103      103
#define T__104      104
#define ADD      4
#define AND      5
#define ARGUMENTS      6
#define ARRAY_ELEMENT      7
#define ARRAY_ELEMENT_INDEX      8
#define ARRAY_ID      9
#define ASSIGN      10
#define BITS      11
#define BLOCK      12
#define BODY      13
#define BREAK      14
#define CALL      15
#define CHAR      16
#define CONDITION      17
#define DEC      18
#define DIGIT      19
#define DIVISION      20
#define DO      21
#define ELSE      22
#define EQUALS      23
#define EXPRESSION      24
#define HEX      25
#define ID      26
#define IDENTIFIER      27
#define IF      28
#define IN_BRACES      29
#define K_ARRAY      30
#define K_BEGIN      31
#define K_BOOL      32
#define K_BREAK      33
#define K_BYTE      34
#define K_CHAR      35
#define K_DO      36
#define K_ELSE      37
#define K_END      38
#define K_FALSE      39
#define K_IF      40
#define K_INT      41
#define K_LONG      42
#define K_METHOD      43
#define K_OF      44
#define K_REPEAT      45
#define K_STRING      46
#define K_THEN      47
#define K_TRUE      48
#define K_UINT      49
#define K_ULONG      50
#define K_UNTIL      51
#define K_VAR      52
#define K_WHILE      53
#define LESS_THAN      54
#define LESS_THAN_OR_EQUALS      55
#define LETTER      56
#define METHOD_DECL      57
#define MORE_THAN      58
#define MORE_THAN_OR_EQUALS      59
#define MULTIPLY      60
#define NOT_EQUALS      61
#define OR      62
#define PARAMETER      63
#define PARAMETERS      64
#define REPEAT      65
#define REPEATABLE_PART      66
#define RESIDUE      67
#define RETURN_TYPE      68
#define SOURCE      69
#define STRING      70
#define SUBTRACT      71
#define THEN      72
#define TYPE      73
#define UNARY_OPERATION      74
#define UNTIL      75
#define VALUE      76
#define VARIABLES      77
#define VAR_DECLARATION      78
#define VAR_DECLARATIONS      79
#define VOID_VALUE      80
#define WHILE      81
#define WS      82
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for GrammarParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
